### ISSUE TITLE
Header files not found on Windows

### ISSUE THREAD

**Issue by jeromekelleher** [conda-forge/gsl-feedstock#49]
I've started to get CI failures on Appveyor, which are possibly caused by the new build in #46. See [here](https://ci.appveyor.com/project/tskit-dev/msprime/builds/27118922) for an example. This was  working fine on build ``gsl-2.5-h294904e_0``, but is now failing on ``gsl-2.5-h631dd0c_1``.

The specific error is:
```
_msprimemodule.c(28): fatal error C1083: Cannot open include file: 'gsl/gsl_version.h': No such file or directory
```

Is anyone else seeing this?

**Comment by jeromekelleher** [comment]
Problem still exists on gsl 2.6

**Comment by jeromekelleher** [comment]
Nope, my bad, sorry for the noise!
